GET http://localhost:3000/todos/?status=TO%2000

###
GET http://localhost:3000/todos/?priority=HIGH

###

GET http://localhost:3000/todos/?category=HOME

###

GET http://localhost:3000/todos/?priority=HIGH&status=DONE

###

GET http://localhost:3000/todos/?category=WORK&status=DONE 

###

GET http://localhost:3000/todos/?category=LEARN&priority=HIGH

###

GET http://localhost:3000/todos/?search_q=Learn
###

GET http://localhost:3000/todos/2/

###

GET http://localhost:3000/agenda/?date=2020-12-22
###

PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
      "dueDate": "2020-09-23"
    }

    ###
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}
###

DELETE http://localhost:3000/todos/:todoId/
Content-Type: application/json